setwd("C:/Users/HP/Desktop/locus")
library(vegan)
alpha<-read.csv("alpha.csv",header = T,row.names = 1)
shannon <- diversity(alpha,index="shannon")
simpson <- diversity(alpha,index="simpson")
invsimpson <- diversity(alpha,index="invsimpson")
observed_microbes<-specnumber(alpha)
alphadata <- data.frame(shannon,simpson,invsimpson,observed_microbes)
write.csv(alphadata,"alphadata.csv")
