TOP<-4
TAIL<-3
library(edgeR)
exprSet <- read.table("1.txt",header=T,row.names = 1,sep = "\t")
head(exprSet)
#exprSet <- round(exprSet * 1e9)
col_names <- colnames(exprSet)
selected_cols <- c(head(col_names, TOP), tail(col_names, TAIL))
expr_sub <- exprSet[, selected_cols]
exprSet <- expr_sub
head(exprSet)
#group <- factor(c("W","W","W","PK","PK", "PK"))
group <- factor(rep(c("LC", "PK"), times = c(TOP, TAIL))) 
factor(group)
design <- model.matrix(~0+factor(group))
colnames(design) <- levels(factor(group))
rownames(design) <- colnames(exprSet)
head(design)
deg <- DGEList(counts=exprSet, group=factor(group))
deg <- calcNormFactors(deg)
deg <- estimateGLMCommonDisp(deg,design)
deg <- estimateGLMTrendedDisp(deg, design)
deg <- estimateGLMTagwiseDisp(deg, design)
fit <- glmFit(deg, design)
lrt <- glmLRT(fit, contrast=c(1,-1)) 
DEG_edgeR <- as.data.frame(topTags(lrt, n=nrow(deg)))
DEG_edgeR <- na.omit(DEG_edgeR)
head(DEG_edgeR)
write.table(DEG_edgeR,"4-vs-3.DEG_edgeR_symbol.xls",sep="\t",quote = F)
